esphome:
  name: transit-tracker-s3
  friendly_name: Transit Tracker

esp32:
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

psram:
  mode: quad
  speed: 80MHz

external_components:
  - source:
      type: local
      path: ../components

logger:
  level: DEBUG
  logs:
    sensor: ERROR
    text_sensor: ERROR

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: "NONE"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TransitTracker Fallback Hotspot"
    password: "59541bEJiaf3"

display:
  - platform: hub75
    id: matrix
    board: adafruit-matrix-portal-s3
    double_buffer: true
    update_interval: 32ms
    panel_width: 64
    panel_height: 32
    layout_cols: 2
    # We swap the G and B channels in firmware because the 64x32 panel hardware has them reversed
    g1_pin: 40
    b1_pin: 41
    g2_pin: 37
    b2_pin: 39
    e_pin: 21
    brightness: 255
    lambda: |-
      id(tracker).draw_schedule();

font:
  - file: "fonts/Pixolletta8px.ttf"
    id: pixolletta
    size: 10
    glyphs:
      - abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,:;!?()"'-+/*=%@#[]{}<>|&^~
      - " "

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles

color:
  - id: route_44_purple
    hex: "840AFD"
  - id: e_line_red
    hex: "9C182F"

transit_tracker:
  id: tracker
  base_url: "wss://tt.horner.tj/"
  limit: 12
  feed_code: "st"
  list_mode: "doubleTime"
  scroll_headsigns: true
  show_units: "short"
  stops:
    - stop_id: "1_29557" # Route 44 @ UW
      routes:
        - "1_100224" # 44
    - stop_id: "1_29231" # Route 44 @ Ballard
      routes:
        - "1_100224" # 44
    - stop_id: "1_75408" # E Line @ Downtown
      routes:
        - "1_102615" # E Line
  styles:
    - route_id: "1_100224"
      name: "44"
      color: route_44_purple
    - route_id: "1_102615"
      name: "E"
      color: e_line_red
  abbreviations:
    - from: "Seattle"
      to: ""
    - from: "Ballard Wallingford"
      to: "Ballard"
    - from: "University Of Washington Medical Center Wallingford"
      to: "UW"
    - from: "University District"
      to: "UW"
